name: build

on:
  workflow_dispatch:
  
  pull_request:
    branches: [ main ]
    paths:
      - '_build/**'
      - '.github/workflows/*.yaml'
  
  pull_request_target:
    branches: [ main ]
    paths-ignore:
      - '_build/**'
      - '.github/workflows/*.yaml'

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Add DevExpress source: https://docs.devexpress.com/GeneralInformation/117209/installation/install-devexpress-controls-using-nuget-packages/manage-packages-with-dotnet-cli
      - name: Add DevExpress package source
        run: dotnet nuget add source https://nuget.devexpress.com/api -n DXFeed -u DevExpress -p ${{ secrets.DEVEXPRESS_FEED_URL }}
      
      # Build docs
      - name: Run './build.cmd '
        run: ./build.cmd compile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Upload docs site: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin